### ISSUE TITLE
InstanceGroup Requires "OpenShift or Kubernetes credential"

### ISSUE THREAD

**Issue by neevgef** [ansible/awx-resource-operator#161]
InstanceGroup CRD sets credential_name as required even tho it is not required when specifying the InstanceGroup.
I propose we remove the credential_name from required.

[Instance Group CRD required](https://github.com/ansible/awx-resource-operator/blob/270c21758d82a745376f9e38ac43d92380d0f593/config/crd/bases/tower.ansible.com_ansibleinstancegroups.yaml#L73C15-L73C30)

Moreover, there should be a fieldDependency set in the ClusterServiceVersion, for the InstanceGroup:
For example, the credential_name only exists for containerGroups:
```
     - displayName: Container Group
        path: is_container_group
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: OpenShift or Kubernetes credential
        path: credential_name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:fieldDependency:is_container_group:true
```
While "policy_instance_minimum" and "policy_instance_percentage" only exists for instanceGroups (and not containerGroups):
 ```
     - displayName: Policy Instance Percentage
        path: policy_instance_percentage
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:int
        - urn:alm:descriptor:com.tectonic.ui:fieldDependency:is_container_group:false
      - displayName: Policy Instance Minimum
        path: policy_instance_minimum
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:int
        - urn:alm:descriptor:com.tectonic.ui:fieldDependency:is_container_group:false
```
