### ISSUE TITLE
TTL Controller for Finished Resources causes AnsibleJobs to run repeatedly

### ISSUE THREAD

**Issue by gparvin** [ansible/awx-resource-operator#49]
In OCP 4.8 https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/ is enabled by default.
This means jobs get deleted after an hour.  When the job gets deleted, it seems the AnsibleJob wants to re-run the automation again.  This causes the automation to run hourly.

The feature gate for `TTL Controller for Finished Resources` can be disabled which I think will prevent this from happening.  I'm trying that out now.  To disable you do this:

Run: `oc edit kubeapiservers.operator.openshift.io cluster` and then update the `unsupportedConfigOverrides`

```
  unsupportedConfigOverrides: 
    apiServerArguments:
      feature-gates:
      - TTLAfterFinished=false
```

It would be nice if the AnsibleJob status could be used to prevent the re-run to allow job cleanup to work.
