### ISSUE TITLE
Resource Operator or Ansible awx module

### ISSUE THREAD

**Issue by hungtran84** [ansible/awx-resource-operator#60]
Currently I bootstrap awx on top of Azure AKS with LDAP integration at the beginning. Since we adopt gitops, everything must/should be checked in code including awx setting (like LDAP, proxy, ...) and awx resources.

In a perfect world, awx and its core resources: credential/inventory/project/template are able to be provisioned via manifest files at boot and keep updating with SCM. As your work on this repo just covered template and job only for now, do you have any plan for other resources? It is possible to re-use Ansible awx module? Eg:

```yaml
    - name: Create a valid SCM credential 
      awx.awx.credential:
        name: my_git
        organization: '{{ org }}'
        state: present
        credential_type: Source Control
        inputs:
          username: '{{ git_user }}'
          password: '{{ git_token }}'

    - name: Add DRE project
      awx.awx.project:
        name: my_project
        description: Set of Ansible playbooks developed by XYZ
        organization: '{{ org }}'
        credential: '{{ git_credential }}'
        scm_type: git
        scm_branch: main
        scm_update_on_launch: yes
        scm_url: https://myGitServer/abc/xyz
        validate_certs: no
        state: present
        wait: no
```

I'll be crazy happy if these resource can be created with operator rather than running it from my local as an AWX seed playbook.

Thank you,
